export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE';
export const LOADING_TRUE='LOADING_TRUE'
export const LOADING_FALSE='LOADING_FALSE'
export const LOADING='LOADING'
export const ERROR='ERROR'
export const ERROR_MSG='ERROR_MSG'